### ISSUE TITLE
Review CSV Documentation in Swagger

### ISSUE THREAD

**Issue by Chris-Schnaufer** [PecanProject/BETYdb-YABA#10]
@dlebauer @kimberlyh66 @gsrohde I have added the schema of CSV in Swagger under examples .Now i implemented for experiments endpoint only.
https://app.swaggerhub.com/apis/y51/bet-ydb_yaba/1.0.5#/experiments/Meta.insert_experiments

Here only i added the columns and one row as example.

Please review it.

**Comment by gsrohde** [comment]
The first thing that strikes me is that the example mixes the use of sample values ("MAC Season 8: Border", "2019-01-01", and "2019-03-31") with what seem to be value descriptors ("text").  It would be better if sample values were used in the `description` and `design` columns as well.

Second, it's too bad that the Swagger display doesn't display this information in the right-most panel as it did when a JSON content type was used.  But I'm assuming this is a limitation of Swagger and there is nothing to be done about this.

Third, and especially since the CSV file format is not fully-standardized, it would be helpful to have a more complete specification of the file requirements.  Whether this belongs in the Swagger documentation itself (is a "comments" field allowed?) or in some separate document (perhaps with a reference in the Swagger documentation) is an open question.  It would admittedly be rather repetitive to include this information for each endpoint, since the general CSV requirements would likely be largely the same.  Questions a user might have that would not be answered by extrapolating from the example include
1. Can commas, double-quote marks, and newline characters be included in a field value?  If so, how should the field be delimited?  Assuming double-quotes can and should be used for this purpose, how should double quotes that are part of the field value be represented?
2. What newline conventions are acceptable, e.g., DOS-style, MAC-style, UNIX-style, a mixture?
3. Can non-ascii characters be included, and if so, how should they be encoded?
4. Does the file need to end with a newline character?

In addition to the CSV requirements, each field of each endpoint might impose additional requirements.  For example, does an experiment `start_date` value _have_ to be in the form YYYY-MM-DD, or are other common date formats (e.g. "31 Mar 2019", "March 31, 2019", "03-31-2019") allowed as well?

I hope you won't think I'm nitpicking to point out a few other things:

1. In example/CSV/summary, there should be a space after the period, "Upload" shouldn't be capitalized, and you should say "CSV file" (preferred) or "csv file" but not alternate.
2. Regarding the responses section, I was surprised to learn that a string on its own is valid JSON.  This is apparently [a change](https://stackoverflow.com/questions/7487869/is-this-simple-string-considered-valid-json).  Still, I was baffled by examples such as
```
 |-
                ERROR - Uploaded file does not meet the standards.Check the columns
                ERROR - Uploaded file does not have appropriate columns
                ERROR - File for wrong table is uploaded
```
Is this one example or three?  (If the latter, using an `examples` field is more appropriate.)  And is there significance to the "|-"?  Strictly speaking, I think JSON strings must be on a single line, but sometimes YAML is used to represent a JSON document; or maybe this some Swagger or OpenAPI convention.  So perhaps I'm taking this example value too literally.
3. It seems to me that the format of the `fileName` string doesn't have to be binary.  Usually, I would think, this would be human-readable text.
