### ISSUE TITLE
Review swaggerhub specification 

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/BETYdb-YABA#6]
@kimberlyh66 please 

* review the BETYdb-YABA API 
  * Specification on Swaggerhub https://app.swaggerhub.com/apis-docs/y51/bet-ydb_yaba/0.0.1
  * openapi specification https://github.com/PecanProject/BETYdb-YABA/blob/master/yaba.yaml
  * [x] Compare endpoints to the documentation in OSF / functions you have created.
* Fork the version @saurabh1969 put on swaggerhub https://app.swaggerhub.com/apis/y51/bet-ydb_yaba/0.0.1
   * [x] Improve / expand documentation where possible
   * [x] suggest any other changes

**Comment by saurabh1969** [comment]
@kimberlyh66 use this for Swagger specifications on Swaggerhub :[https://app.swaggerhub.com/apis-docs/y51/bet-ydb_yaba/1.0.4](https://app.swaggerhub.com/apis-docs/y51/bet-ydb_yaba/1.0.4)

**Comment by Chris-Schnaufer** [comment]
Kimberly please summarize conclusions

**Comment by kimberlyh66** [comment]
@saurabh1969 The swagger specification looks good!

I just have a few minor comments/questions: 

* I think that `username` is only needed to upload data to the `experiments` table. So the `username` parameter is not needed for the treatments and citations endpoints.

* Tags for the experiments_sites and experiments_treatments endpoints are using `experiment_` instead of `experiments_`

* Where are you planning to document what data should be included in each file that will be uploaded for each endpoint? Is there a way to include this in the swagger specification?

**Comment by gsrohde** [comment]
Coming at this without really having kept up on this project task, I thought it worth pointing out that the following BETYdb tables all have a `user_id` column: `benchmarks`, `benchmarks_ensembles`, `benchmarks_ensembles_scores`, `managements`, `modeltypes_formats`, `modeltypes`, `metrics`, `sitegroups`, `inputs`, `reference_runs`, `benchmark_sets`, `traits`, `citations`, `sites`, `yields`, `treatments`, `workflows`, `experiments`.  In particular, the `treatements` and `citations` table both store user id information.

Ignore this if there is some definite reason for not storing this information for these two endpoints.

**Comment by dlebauer** [comment]
@gsrohde thank you for your feedback - something we haven't considered is user credentials, but once we implement it I expect that we can use the api key to find the user name and populate these fields, so they don't need to be explicitly part of the API, correct?

**Comment by gsrohde** [comment]
@dlebauer Yes, that seems correct to me.  In fact, it not only doesn't _need_ to be part of the API, I would say it _shouldn't_ be: you don't want users being able to spoof the name of the user responsible for adding the data.

**Comment by gsrohde** [comment]
Here are some other comments on this API:

experiments: As you suggest, `user_id` should be eliminated from the request body.  In the description, the name of table should match the case of the table name in the database, and "Table" should be "table".  In other words, the description should read "Upload metadata to the experiments table" (possibly with a period at the end).  Similarly for all of the other descriptions.  I could go on to say there is something semantically unsatisfying about the description "Upload metadata to the experiments table", as if something else could also be uploaded to the experiments table.  Less obscure would be "Add an experiment to the experiments table."  If you are going to stick with "Upload metadata ...", be consistent.  All three of "metadata", "meta-data", and "meta data" are used in the descriptions.

cultivars: `id` is presumably the species id.  It would be better to use `species_name` instead and have the API implementation look up the correct species id in the species table.  See below.

experiment_sites: As noted, this should be `experiments_sites`.  Likewise, the description should read "Upload metadata to the experiments_sites table".  `specie_name` presumably was meant to be `site_name`.

experiment_treatments: As noted, this should be `experiments_treatments`.  Likewise, the description should read "Upload metadata to the experiments_treatments table". 

sites_cultivars: It would be preferable to use `species_name` and look up the correct `specie_id` value in the species table by finding the row whose `scientificname` value matches the species value in the request.  Unfortunately, even though there is a tacit understanding the `scientificname` column values should uniquely identify the species, there is currently no database guarantee that at most one row will be matched.  See additional comments below.

citations_sites: `citations_name` was presumably meant to be `site_name` since the three other keys serve to identify the citation and there is no other identification of the site.  It would be clearer to use `citation_author`, `citation_year`, and `citation_title` in place of `author_name`, `year`, and `title`.


General comments:

In general, it is best if each request hash corresponds to a meaningful predicate, one which doesn't require the user to know anything about the implementation of data storage.  For example, the predicate for the `sites` endpoint might be

> There is a site which we have chosen to call `sitename` which is located in or near the city `city` in the state `state` in the country `country`.

Given the hash
```
{
  "city": "Maricopa",
  "state": "Arizona",
  "country": "USA",
  "sitename": "MAC Field Scanner Season 7 Range 9 Column 15"
}
```
This becomes
> There is a site which we have chosen to call "MAC Field Scanner Season 7 Range 9 Column 15"
 which is located in or near the city "Maricopa" in the state "Arizona" in the country "USA".

For the endpoint `sites_cultivars`, the predicate is presumably something like "The site which we are calling `site_name` is planted with a cultivar of the species with id number `specie_id` named `cultivar_name`."  It would be better if the predicate were "The site which we are calling `site_name` is planted with a cultivar of the species `species_name` named `cultivar_name`."

One might argue that it would be better not to have to look up the species id each time a `sites_cultivars` row is added.  It should be pointed out, however, that additions to any of the other join tables will entail similar such lookups.  For example, a request to the `experiments_treatments` table supplies an experiment name and treatment name, and the ids for these will have to be looked up in the respective tables before a row can be added to the `experiments_treatments` table.

In many if not most of these cases, the database gives no guarantee that the lookups will yield at most one value.  In the event that multiple rows use the same name, the API should return an error.  But it would be better if the database were changed to ensure this never happens.

**Comment by dlebauer** [comment]
@KristinaRiemer please discuss tomorrow at your meeting and create new issues then close

**Comment by KristinaRiemer** [comment]
@kimberlyh66 @gsrohde your suggestions have been implemented in the most recent version of the Swaggerhub, which is here: https://app.swaggerhub.com/apis-docs/y51/bet-ydb_yaba/1.0.4. If you just want to review that version to make sure you have no further comments, that would be great.

**Comment by gsrohde** [comment]
@KristinaRiemer 
This newest version uses HTTP content type `multipart/form-data` in place of `application/json` used by the previous versions.  Presumably this is because the API is now projected to use uploads of CSV files in place of JSON data in making requests.  But whereas the previous version gave sample values for the form of the JSON data, this version doesn't say anything about the format of the CSV files to be submitted.  So I can't really tell from the Swaggerhub document whether my concerns have been addressed.

**Comment by kimberlyh66** [comment]
@KristinaRiemer I am not sure if the third bullet of my comments can be addressed (documentation for the csv files) with the swagger specification

**Comment by dlebauer** [comment]
I think that removing the json made all of the documentation disappear. We should discuss this design. Perhaps document the json and accept either json or equivalent as csv.

Next step is to discuss b/w/ Kimberly, David, Kristina and anyone else who is interested.

**Comment by saurabh1969** [comment]
@dlebauer @kimberlyh66 @gsrohde I have added the schema of CSV in Swagger under examples .Now i implemented for experiments endpoint only.
[https://app.swaggerhub.com/apis/y51/bet-ydb_yaba/1.0.5#/experiments/Meta.insert_experiments](https://app.swaggerhub.com/apis/y51/bet-ydb_yaba/1.0.5#/experiments/Meta.insert_experiments)

Here only i added the columns and one row as example.

Please review it.
